version: '3'
services:

services:
    server:
        image: nginx:alpine
        restart: always
        depends_on:
            - web
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - public:/code/public

    web:
        image: harmonysword/tp5.1-3:latest
        command: bash -c "/code/run.sh"
        restart: always
        env_file:
            - ../const.env
        volumes:
            - public:/code/public

volumes:
    public: